### ISSUE TITLE
Syntax error in ubuntu in 18.04

### ISSUE THREAD

**Issue by pkncsk** [Tibowl/KCCacheProxy#3]
Hi, 
Thank you Tibowl for creating such a wonderful app. It works just fine for windows 10, but when I tried to run it on linux, it gave me this error:

```
/Downloads/KCCacheProxy-linux$ nodejs proxy-linux 
/home/user/Downloads/KCCacheProxy-linux/proxy-linux:1
(function (exports, require, module, __filename, __dirname) { ELF
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
I have no knowledge about node.js, so, is there any way to solve this error?

**Comment by Tibowl** [comment]
You could try running the normal node version instead of the compiled versions. 
[Here's some instructions on how to set it up](https://github.com/Tibowl/KCCacheProxy/blob/master/ReadMe.md#setup-using-node). TLDR; It's basically install node.js (`apt-get install nodejs`) and then run `proxy node`

**Comment by pkncsk** [comment]
It works! Thank you very much.
